#!/usr/bin/ansible-playbook
---
- name: Setup inventory
  hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - vars.yml

  roles:
    - name: security
    - name: repos
    - name: packages
    - name: preferences
