set tabstop=2 softtabstop=2 expandtab shiftwidth=2
colorscheme ron

set nocompatible
syntax enable
filetype plugin on

set number

set path+=**
set wildmenu

let g:netrw_banner=0
let g:netrw_browse_split=4
let g:netrw_altv=1
let g:netrw_liststyle=3
