---
- name: Send over vimrc
  copy:
    src: vimrc
    dest: ~/.vimrc

- name: Send over tmux.conf
  copy:
    src: tmux.conf
    dest: ~/.tmux.conf

- name: Send over gitconfig
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig
